routes/web.php
<?php

use App\Resource;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* View of quote for client */
Route::get('/view/{token}/{quote}','MailsController@view')->name('email.view');
Route::get('/quote/exit','MailsController@exit')->name('email.exit');
/* Route for mail sending */
Route::get('/send/{quote}', 'MailsController@send')->name('email.send');
Route::get('/send/accept/{quote}','MailsController@accept')->name('email.accept');
Route::post('/send/refuse/{quote}', 'MailsController@refuse')->name('email.refuse');
/* Route for pdf generation */
Route::get('/generate-pdf/{id}','PDFController@pdf_download')->name('email.pdf_download');
Route::get('/download/{id}', 'PDFController@download')->name('email.download');

Auth::routes();

// Route::get('/', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::view('/', 'example');
    /* Clients */
    Route::resource('clients', 'ClientsController');
    /* Services */
    Route::get('/{client}/services/create', 'ServicesController@create')->name('services.create');
    Route::post('/{client}/services/store', 'ServicesController@store')->name('services.store');
    Route::delete('/services/delete/{service}', 'ServicesController@destroy')->name('services.destroy');
    /*  Services Details */
    Route::patch('/services_details/update/{service_detail}','ServicesDetailsController@update')->name('services_detail.update');
    Route::delete('/services_details/delete/{service_detail}','ServicesDetailsController@destroy')->name('services_detail.destroy');
    /* Requirements */
    Route::get('/requirements', 'RequirementsController@index')->name('requirements.index');
    Route::get('/requirements/show/{requirement}', 'RequirementsController@show')->name('requirements.show');
    Route::resource('requirements', 'RequirementsController', ['except' => ['index', 'show']]);
    /* Users */
    Route::resource('users', 'UsersController');
    /* Resources */
    Route::resource('resources', 'ResourcesController', ['except' => ['show']]);
    /* Task */
    Route::get('/tasks/calendar','TasksController@calendar')->name('tasks.calendar');
    Route::post('/task/{requirement}/store', 'TasksController@store')->name('tasks.store');
    Route::get('/task/{task}/clickup','TasksController@Project_Task')->name('tasks.Project_Task');
    Route::post('task/{task}/project','TasksController@Project')->name('tasks.Project');
    Route::post('/task/{task}/postTask','TasksController@postTask')->name('tasks.postTask');
    Route::resource('tasks', 'TasksController', ['except' => ['create', 'store']]);
    /* Quotes */
    Route::post('/quotes/{requirement}/store', 'QuotesController@store')->name('quotes.store');
    Route::resource('quotes', 'QuotesController', ['except' => ['create', 'store']]);
    /* Quotes Details*/
    Route::post('/quotes_details/{quote}/store', 'Quotes_DetailsController@store')->name('quotes_details.store');
    Route::patch('/quotes_details/{quote_detail}/update', 'Quotes_DetailsController@update')->name('quotes_details.update');
    Route::delete('/quotes_details/{quote_detail}', 'Quotes_DetailsController@destroy')->name('quotes_details.destroy');
    /* Roles */
    Route::resource('roles', 'RolesController');

    /* Api */
    Route::get('/api/resource/{resource}', function (Resource $resource) {
        return $resource;
    });

    /* Statuses */
    Route::resource('statuses', 'StatusesController');

    /* Sources */
    Route::resource('sources', 'SourcesController');

    /* Types */
    Route::resource('types', 'TypesController');


    /* Providers */
    Route::resource('providers','ProvidersController', ['except' => ['create', 'store','edit']]);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $with = ['role'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function clients()
    {
        return $this->belongsToMany(Client::class, 'client_users', 'user_id', 'client_id');
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function hasClient($id)
    {
        return in_array($id, $this->clients->pluck('id')->toArray());
    }

    public function contact()
    {
        return $this->hasMany('App\User','contact_id');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\User;
use App\Client;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        $clients = Client::all();

        return view('users.create', compact('roles', 'clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages=[
            'name.required'=>'Nombre requerido.',
            'password.required'=>'Contraseña requerida',
            'password.min'=>'Contraseña debe tener mínimo 6 caracteres.',
            'email.required'=>'Email requerido.',
            'email.email'=>'Error, ejemplo: kicktask@example.com',
            'email.unique'=>'Email ya en uso, ingrese uno nuevo.',
            'phone.required'=>'Teléfono requerido.',
            'legal_id.required'=>'Cédula requerido.',
            'legal_id.numeric'=> 'Cédula debe ser numérico.',
            'legal_id.min'=>'Cédula debe tener mínimo 10 número.',
            'address.required'=>'Dirección requerida.',
            'role_id.required'=>'Seleccione un rol.'
        ];

        $this->validate($request, [
            'name' => 'required|string',
            'email' => 'required|email|unique:users,email',
            'password' => 'sometimes|required|min:6',
            'phone' => 'sometimes|required',
            'address' => 'sometimes|required',
            'legal_id' => 'sometimes|numeric|min:10',
            'role_id' => 'required|exists:roles,id',
        ],$messages);

        $user = new User($request->except(['clients', 'password']));
        $user->password = bcrypt($request->password);
        $user->save();

        if ($request->has('clients')) {
            $user->clients()->sync($request->clients);
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $client = Client::where('id',$user->client_id);
        $roles = Role::all();

        return view('users.show', compact('user', 'client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $clients = Client::all();
        $roles = Role::all();

        return view('users.edit', compact('user', 'clients', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'email' => [
                'required',
                'email',
                Rule::unique('users')->ignore($user->id)
            ],
            'password' => 'nullable|min:6',
            'phone' => 'sometimes|numeric',
            'legal_id' => 'sometimes|numeric|min:10',
            'role_id' => 'required|exists:roles,id',
        ]);

        $user->fill($request->except(['clients', 'password']));

        if ($request->filled('password')) {
            $user->password = bcrypt($request->password);
        }

        $user->save();

        if ($request->has('clients')) {
            $user->clients()->sync($request->clients);
        }

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->clients()->detach(); // ELIMINAR ESTO
        $user->delete();

        return redirect()->route('users.index');
    }
}

resources/views/users/create.blade.php
@extends('layouts.layout') @section('content')
<!-- BEGIN: Subheader -->
@breadcrumbs(['title' => 'Agregar Usuario'])
<li class="m-nav__item m-nav__item--home">
    <a href="/" class="m-nav__link m-nav__link--icon">
        <i class="m-nav__link-icon la la-home"></i>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{ route("clients.index") }}" class="m-nav__link">
        <span class="m-nav__link-text">Usuarios</span>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{ route("clients.create") }}" class="m-nav__link">
        <span class="m-nav__link-text">Crear</span>
    </a>
</li>
@slot('options')
@endslot 
@endbreadcrumbs
<!-- END: Subheader -->
<div class="m-content">
    <!--Section-->
    <div class="m-portlet">
        <div class="m-portlet__body m-portlet__body--no-padding">
            <div class="row m-row--no-padding m-row--col-separator-xl">
                <div class="m-portlet col mb-0">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text"> Ingrese los detalles del usuario</h3>
                            </div>
                        </div>
                    </div>
                    <form class="m-form m-form--fit m-form--label-align-right m-form--state col-md-6 pl-0" method="post" action="{{route('users.store')}}">
                        @csrf
                        <div class="form-group m-form__group @if($errors->has('name')) has-danger @endif">
                            <label for="name"> Nombre:</label>
                            <input  id="name" class="form-control m-input m-input--square" name="name"  placeholder="Ingrese Nombre">
                            @if($errors->has('name'))
                                <div class="form-control-feedback">{{ $errors->first('name') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('name')) has-danger @endif">
                            <label for="email"> Correo:</label>
                            <input type="email" id="email" class="form-control m-input m-input--square" name="email" aria-describedby="emailHelp" placeholder="Ingrese correo">
                            @if($errors->has('email'))
                                <div class="form-control-feedback">{{ $errors->first('email') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('password')) has-danger @endif">
                            <label for="password"> Contraseña:</label>
                            <input type="password" id="password" class="form-control m-input m-input--square" name="password" aria-describedby="password" placeholder="Ingrese contraseña">
                            @if($errors->has('password'))
                                <div class="form-control-feedback">{{ $errors->first('password') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('phone')) has-danger @endif">
                            <label for="phone"> Teléfono:</label>
                            <input type="text" id="phone" class="form-control m-input m-input--square" name="phone" placeholder="Ingrese teléfono">
                            @if($errors->has('phone'))
                                <div class="form-control-feedback">{{ $errors->first('phone') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('legal_id')) has-danger @endif">
                            <label for="legal_id"> Cédula/R.U.C:</label>
                            <input type="text" class="form-control m-input m-input--square" name="legal_id" placeholder="Ingrese cédula o R.U.C">
                            @if($errors->has('legal_id'))
                                <div class="form-control-feedback">{{ $errors->first('legal_id') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('address')) has-danger @endif">
                            <label for="address"> Dirección:</label>
                            <input type="text" class="form-control m-input m-input--square" name="address" placeholder="Ingrese dirección">
                            @if($errors->has('address'))
                                <div class="form-control-feedback">{{ $errors->first('address') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('role_id')) has-danger @endif">
                            <label for="role_id"> Rol:</label>
                            <select name="role_id" id="role_id" class="selectpicker bootstrap-select form-control m-bootstrap-select">
                                <option value="">Seleccionar rol</option>
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('role_id'))
                                <div class="form-control-feedback">{{ $errors->first('role_id') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('clients')) has-danger @endif">
                            <label for="clients"> Clientes:</label>
                            <select class="form-control m-select2" id="clients" name="clients[]" multiple="multiple">
                                <option></option>
                                @foreach ($clients as $client)
                                    <option value="{{ $client->id }}">{{ $client->name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('clients'))
                                <div class="form-control-feedback">{{ $errors->first('clients') }}</div>
                            @endif
                        </div>
                        <div class="m-form__actions">
                            <a href="{{ route("users.index")}}" class="btn btn-metal">Cancelar</a>
                            <button type="submit"  class="btn btn-success">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $('#clients').select2({
            placeholder: "Seleccionar clientes",
        });
    </script>
@endpush

resources/views/users/edit.blade.php
@extends('layouts.layout') @section('content')
<!-- BEGIN: Subheader -->
@breadcrumbs(['title' => 'Editar Usuario'])
<li class="m-nav__item m-nav__item--home">
    <a href="/" class="m-nav__link m-nav__link--icon">
        <i class="m-nav__link-icon la la-home"></i>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{ route("clients.index") }}" class="m-nav__link">
        <span class="m-nav__link-text">Usuarios</span>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{ route("users.edit", $user) }}" class="m-nav__link">
        <span class="m-nav__link-text">Editar</span>
    </a>
</li>
@slot('options')
@endslot 
@endbreadcrumbs
<!-- END: Subheader -->
<div class="m-content">
    <!--Section-->
    <div class="m-portlet">
        <div class="m-portlet__body m-portlet__body--no-padding">
            <div class="row m-row--no-padding m-row--col-separator-xl">
                <div class="m-portlet col mb-0">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text"> Ingrese los detalles del usuario</h3>
                            </div>
                        </div>
                    </div>
                    <form class="m-form m-form--fit m-form--label-align-right m-form--state col-md-6 pl-0" method="post" action="{{route('users.update', $user)}}">
                        @csrf
                        @method('PATCH')
                        <div class="form-group m-form__group @if($errors->has('name')) has-danger @endif">
                            <label for="name"> Nombre:</label>
                            <input  id="name" class="form-control m-input m-input--square" name="name" value="{{ $user->name }}"  placeholder="Ingrese Nombre">
                            @if($errors->has('name'))
                                <div class="form-control-feedback">{{ $errors->first('name') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('name')) has-danger @endif">
                            <label for="email"> Correo:</label>
                            <input type="email" id="email" class="form-control m-input m-input--square" name="email" aria-describedby="emailHelp" value="{{ $user->email }}" placeholder="Ingrese correo">
                            @if($errors->has('email'))
                                <div class="form-control-feedback">{{ $errors->first('email') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('password')) has-danger @endif">
                            <label for="password"> Contraseña:</label>
                            <input type="password" id="password" class="form-control m-input m-input--square" name="password" aria-describedby="password" placeholder="Ingrese contraseña">
                            @if($errors->has('password'))
                                <div class="form-control-feedback">{{ $errors->first('password') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('phone')) has-danger @endif">
                            <label for="phone"> Teléfono:</label>
                            <input type="text" id="phone" value="{{ $user->phone }}" class="form-control m-input m-input--square" name="phone" placeholder="Ingrese teléfono">
                            @if($errors->has('phone'))
                                <div class="form-control-feedback">{{ $errors->first('phone') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('legal_id')) has-danger @endif">
                            <label for="legal_id"> Cédula/R.U.C:</label>
                            <input type="text" value="{{ $user->legal_id }}" class="form-control m-input m-input--square" name="legal_id" placeholder="Ingrese cédula o R.U.C">
                            @if($errors->has('legal_id'))
                                <div class="form-control-feedback">{{ $errors->first('legal_id') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('address')) has-danger @endif">
                            <label for="address"> Dirección:</label>
                            <input type="text" value="{{ $user->address }}" class="form-control m-input m-input--square" name="address" placeholder="Ingrese dirección">
                            @if($errors->has('address'))
                                <div class="form-control-feedback">{{ $errors->first('address') }}</div>
                            @endif
                        </div>
                        <div class="form-group m-form__group @if($errors->has('role_id')) has-danger @endif">
                            <label for="role_id"> Rol:</label>
                            <select name="role_id" id="role_id" class="selectpicker bootstrap-select form-control m-bootstrap-select">
                                <option value="">Seleccionar rol</option>
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}" @if($user->role->id === $role->id) selected @endif>{{ $role->name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('role_id'))
                                <div class="form-control-feedback">{{ $errors->first('role_id') }}</div>
                            @endif
                        </div>

                        <div class="form-group m-form__group @if($errors->has('clients')) has-danger @endif">
                            <label for="clients"> Clientes:</label>
                            <select class="form-control m-select2" id="clients" name="clients[]" multiple="multiple">
                                <option></option>
                                @foreach ($clients as $client)
                                    <option value="{{ $client->id }}" @if($user->hasClient($client->id)) selected @endif>{{ $client->name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('clients'))
                                <div class="form-control-feedback">{{ $errors->first('clients') }}</div>
                            @endif
                        </div>
                        <div class="m-form__actions">
                            <a href="{{ route("users.index")}}" class="btn btn-metal">Cancelar</a>
                            <button type="submit"  class="btn btn-success">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $('#clients').select2({
            placeholder: "Seleccionar clientes",
        });
    </script>
@endpush

resources/views/users/index.blade.php
@extends('layouts.layout') 

@section('content')
<!-- BEGIN: Subheader -->
@breadcrumbs(['title' => 'Usuarios'])
<li class="m-nav__item m-nav__item--home">
    <a href="/" class="m-nav__link m-nav__link--icon">
        <i class="m-nav__link-icon la la-home"></i>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{route('users.index')}}" class="m-nav__link">
        <span class="m-nav__link-text">Usuarios</span>
    </a>
</li>
@slot('options')
<a href="{{ route('users.create') }}" class="btn btn-primary">Agregar usuario</a>
@endslot 
@endbreadcrumbs
<!-- END: Subheader -->

<div class="m-content">
    <!--Section-->
    <div class="m-portlet">
        <div class="m-portlet__body m-portlet__body--no-padding">
            <div class="row m-row--no-padding m-row--col-separator-xl">
                <div class="m-section col mb-0">
                    <div class="m-section_content">
                        <table class="table table-bordered m-table m-table--head-bg-brand mb-0">
                            <thead>
                                <tr>
                                    <th class="m--img-centered">#</th>
                                    <th class="m--img-centered">Nombre</th>
                                    <th class="m--img-centered">Email</th>
                                    <th class="m--img-centered">Cédula</th>
                                    <th class="m--img-centered">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td class="m--img-centered" >{{$loop->iteration}}</td>
                                    <td class="m--img-centered">{{ $user->name }}</td>
                                    <td class="m--img-centered">{{ $user->email }}</td>
                                    <td class="m--img-centered">{{ $user->legal_id }}</td>
                                    <td class="m--img-centered">
                                        <a href="{{ route('users.show', [$user])}}" class="btn btn-success btn-sm">
                                            <i class="m-menu__link-icon flaticon-visible"></i>
                                            Ver
                                        </a>
                                        <a href="{{ route('users.edit', [$user])}}" class="btn btn-info btn-sm">
                                            <i class="m-menu__link-icon flaticon-edit"></i>
                                            Editar
                                        </a>

                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#eliminarModal{{$user->id}}">
                                            <i class="m-menu__link-icon flaticon-circle"></i>
                                            Eliminar
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="eliminarModal{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                            aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Eliminar Usuario {{ $user->name }}</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        ¿Está seguro que desea eliminar este usuario?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                        <form action="{{ route('users.destroy', [$user])}}" method="POST">
                                                            @csrf
                                                            @method('delete')
                                                            <button class="btn btn-danger">
                                                                <i class="la la-trash"></i> Eliminar
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection