routes/web.php
<?php

use App\Resource;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* View of quote for client */
Route::get('/view/{token}/{quote}','MailsController@view')->name('email.view');
Route::get('/quote/exit','MailsController@exit')->name('email.exit');
/* Route for mail sending */
Route::get('/send/{quote}', 'MailsController@send')->name('email.send');
Route::get('/send/accept/{quote}','MailsController@accept')->name('email.accept');
Route::post('/send/refuse/{quote}', 'MailsController@refuse')->name('email.refuse');
/* Route for pdf generation */
Route::get('/generate-pdf/{id}','PDFController@pdf_download')->name('email.pdf_download');
Route::get('/download/{id}', 'PDFController@download')->name('email.download');

Auth::routes();

// Route::get('/', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::view('/', 'example');
    /* Clients */
    Route::resource('clients', 'ClientsController');
    /* Services */
    Route::get('/{client}/services/create', 'ServicesController@create')->name('services.create');
    Route::post('/{client}/services/store', 'ServicesController@store')->name('services.store');
    Route::delete('/services/delete/{service}', 'ServicesController@destroy')->name('services.destroy');
    /*  Services Details */
    Route::patch('/services_details/update/{service_detail}','ServicesDetailsController@update')->name('services_detail.update');
    Route::delete('/services_details/delete/{service_detail}','ServicesDetailsController@destroy')->name('services_detail.destroy');
    /* Requirements */
    Route::get('/requirements', 'RequirementsController@index')->name('requirements.index');
    Route::get('/requirements/show/{requirement}', 'RequirementsController@show')->name('requirements.show');
    Route::resource('requirements', 'RequirementsController', ['except' => ['index', 'show']]);
    /* Users */
    Route::resource('users', 'UsersController');
    /* Resources */
    Route::resource('resources', 'ResourcesController', ['except' => ['show']]);
    /* Task */
    Route::get('/tasks/calendar','TasksController@calendar')->name('tasks.calendar');
    Route::post('/task/{requirement}/store', 'TasksController@store')->name('tasks.store');
    Route::get('/task/{task}/clickup','TasksController@Project_Task')->name('tasks.Project_Task');
    Route::post('task/{task}/project','TasksController@Project')->name('tasks.Project');
    Route::post('/task/{task}/postTask','TasksController@postTask')->name('tasks.postTask');
    Route::resource('tasks', 'TasksController', ['except' => ['create', 'store']]);
    /* Quotes */
    Route::post('/quotes/{requirement}/store', 'QuotesController@store')->name('quotes.store');
    Route::resource('quotes', 'QuotesController', ['except' => ['create', 'store']]);
    /* Quotes Details*/
    Route::post('/quotes_details/{quote}/store', 'Quotes_DetailsController@store')->name('quotes_details.store');
    Route::patch('/quotes_details/{quote_detail}/update', 'Quotes_DetailsController@update')->name('quotes_details.update');
    Route::delete('/quotes_details/{quote_detail}', 'Quotes_DetailsController@destroy')->name('quotes_details.destroy');
    /* Roles */
    Route::resource('roles', 'RolesController');

    /* Api */
    Route::get('/api/resource/{resource}', function (Resource $resource) {
        return $resource;
    });

    /* Statuses */
    Route::resource('statuses', 'StatusesController');

    /* Sources */
    Route::resource('sources', 'SourcesController');

    /* Types */
    Route::resource('types', 'TypesController');


    /* Providers */
    Route::resource('providers','ProvidersController', ['except' => ['create', 'store','edit']]);
});

app/Source.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Source extends Model
{
    public $timestamps=false;

    public function requirements()
    {
        return $this->hasMany('App\Source','source_id');
    }
}

app/Http/Controllers/SourcesController.php
<?php

namespace App\Http\Controllers;

use App\Source;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class SourcesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sources = Source::all();
        return view('sources.index', compact('sources'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sources.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|unique:sources,name',
        ]);

        $source = new Source($request->all());
        $source->save();

        return redirect()->route('sources.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Source $source)
    {
        return view('sources.edit', compact('source'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Source $source)
    {
        $this->validate($request, [
            'name' => [
                'required',
                'string',
                Rule::unique('sources')->ignore($source->id)
            ]
        ]);

        $source->fill($request->all());
        $source->save();

        return redirect()->route('sources.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Source $source)
    {
        $source->delete();
        return redirect()->route('sources.index');
    }
}

resources/views/sources/create.blade.php
@extends('layouts.layout')

@section('content')
    <!-- BEGIN: Subheader -->
    @breadcrumbs(['title' => 'Agregar Fuente'])
        <li class="m-nav__item m-nav__item--home">
            <a href="/" class="m-nav__link m-nav__link--icon">
                <i class="m-nav__link-icon la la-home"></i>
            </a>
        </li>
        <li class="m-nav__separator">-</li>
        <li class="m-nav__item">
            <a href="{{ route("sources.index") }}" class="m-nav__link">
                <span class="m-nav__link-text">Fuentes</span>
            </a>
        </li>
        <li class="m-nav__separator">-</li>
        <li class="m-nav__item">
            <a href="{{ route("sources.create") }}" class="m-nav__link">
                <span class="m-nav__link-text">Crear</span>
            </a>
        </li>
        @slot('options')
        @endslot 
    @endbreadcrumbs
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Section-->
        <div class="m-portlet">
            <div class="m-portlet__body m-portlet__body--no-padding">
                <div class="row m-row--no-padding m-row--col-separator-xl">
                    <div class="m-portlet col mb-0">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text"> Ingrese los detalles de la fuente</h3>
                                </div>
                            </div>
                        </div>
                        <form class="m-form m-form--fit m-form--label-align-right m-form--state col-md-6 pl-0" method="post" action="{{route('sources.store')}}">
                            @csrf
                            <div class="form-group m-form__group @if($errors->has('name')) has-danger @endif">
                                <label for="name"> Nombre:</label>
                                <input  id="name" class="form-control m-input m-input--square" name="name"  placeholder="Ingrese Nombre">
                                @if($errors->has('name'))
                                    <div class="form-control-feedback">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                            <div class="m-form__actions">
                                <a href="{{ route("sources.index")}}" class="btn btn-metal">Cancelar</a>
                                <button type="submit"  class="btn btn-success">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

{{--  @push('scripts')
    <script>
        $('#sources').select2({
            placeholder: "Seleccionar clientes",
        });
    </script>
@endpush  --}}

resources/views/sources/edit.blade.php
@extends('layouts.layout')

@section('content')
    <!-- BEGIN: Subheader -->
    @breadcrumbs(['title' => 'Editar Fuente'])
        <li class="m-nav__item m-nav__item--home">
            <a href="/" class="m-nav__link m-nav__link--icon">
                <i class="m-nav__link-icon la la-home"></i>
            </a>
        </li>
        <li class="m-nav__separator">-</li>
        <li class="m-nav__item">
            <a href="{{ route("clients.index") }}" class="m-nav__link">
                <span class="m-nav__link-text">Fuentes</span>
            </a>
        </li>
        <li class="m-nav__separator">-</li>
        <li class="m-nav__item">
            <a href="{{ route("sources.edit", $source) }}" class="m-nav__link">
                <span class="m-nav__link-text">Editar</span>
            </a>
        </li>
        @slot('options')
        @endslot 
    @endbreadcrumbs
    <!-- END: Subheader -->
    <div class="m-content">
        <!--Section-->
        <div class="m-portlet">
            <div class="m-portlet__body m-portlet__body--no-padding">
                <div class="row m-row--no-padding m-row--col-separator-xl">
                    <div class="m-portlet col mb-0">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text"> Ingrese los detalles de la fuente</h3>
                                </div>
                            </div>
                        </div>
                        <form class="m-form m-form--fit m-form--label-align-right m-form--state col-md-6 pl-0" method="post" action="{{ route('sources.update', $source) }}">
                            @csrf
                            @method('PATCH')
                            <div class="form-group m-form__group @if($errors->has('name')) has-danger @endif">
                                <label for="name"> Nombre:</label>
                                <input  id="name" class="form-control m-input m-input--square" name="name" value="{{ $source->name }}"  placeholder="Ingrese Nombre">
                                @if($errors->has('name'))
                                    <div class="form-control-feedback">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                            <div class="m-form__actions">
                                <a href="{{ route("sources.index")}}" class="btn btn-metal">Cancelar</a>
                                <button type="submit"  class="btn btn-success">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sources/index.blade.php
@extends('layouts.layout') 

@section('content')
    <!-- BEGIN: Subheader -->
    @breadcrumbs(['title' => 'Fuentes'])
        <li class="m-nav__item m-nav__item--home">
            <a href="/" class="m-nav__link m-nav__link--icon">
                <i class="m-nav__link-icon la la-home"></i>
            </a>
        </li>
        <li class="m-nav__separator">-</li>
        <li class="m-nav__item">
            <a href="" class="m-nav__link">
                <span class="m-nav__link-text">Fuentes</span>
            </a>
        </li>
        @slot('options')
            <a href="{{ route('sources.create') }}" class="btn btn-primary">Agregar fuente</a>
        @endslot
    @endbreadcrumbs
    <!-- END: Subheader -->

    <div class="m-content">
        <!--Section-->
        <div class="m-portlet">
            <div class="m-portlet__body m-portlet__body--no-padding">
                <div class="row m-row--no-padding m-row--col-separator-xl">
                    <div class="m-section col mb-0">
                        <div class="m-section_content">
                            <table class="table table-bordered m-table m-table--head-bg-brand mb-0">
                                <thead>
                                    <tr>
                                        <th class="m--img-centered">#</th>
                                        <th class="m--img-centered">Nombre</th>
                                        <th class="m--img-centered">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($sources as $source)
                                    <tr>
                                        <td class="m--img-centered" >{{$loop->iteration}}</td>
                                        <td class="m--img-centered">{{$source->name}}</td>
                                        <td class="m--img-centered">
                                            <a href="{{ route('sources.edit', [ 'id'=>$source->id]) }}">
                                                <button type="button" class="btn btn-info btn-sm">Editar</button>
                                            </a>

                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#eliminarModal{{$source->id}}">Eliminar</button>

                                            <!-- Modal -->
                                            <div class="modal fade" id="eliminarModal{{$source->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                                aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">Eliminar Fuente {{ $source->name }}</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            ¿Está seguro que desea eliminar esta fuente?
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                            <form action="{{ route('sources.destroy', [$source]) }}" method="POST">
                                                                @csrf
                                                                @method('delete')
                                                                <button class="btn btn-danger">
                                                                    <i class="la la-trash"></i> Eliminar
                                                                </button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection