routes/web.php
<?php

use App\Resource;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* View of quote for client */
Route::get('/view/{token}/{quote}','MailsController@view')->name('email.view');
Route::get('/quote/exit','MailsController@exit')->name('email.exit');
/* Route for mail sending */
Route::get('/send/{quote}', 'MailsController@send')->name('email.send');
Route::get('/send/accept/{quote}','MailsController@accept')->name('email.accept');
Route::post('/send/refuse/{quote}', 'MailsController@refuse')->name('email.refuse');
/* Route for pdf generation */
Route::get('/generate-pdf/{id}','PDFController@pdf_download')->name('email.pdf_download');
Route::get('/download/{id}', 'PDFController@download')->name('email.download');

Auth::routes();

// Route::get('/', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::view('/', 'example');
    /* Clients */
    Route::resource('clients', 'ClientsController');
    /* Services */
    Route::get('/{client}/services/create', 'ServicesController@create')->name('services.create');
    Route::post('/{client}/services/store', 'ServicesController@store')->name('services.store');
    Route::delete('/services/delete/{service}', 'ServicesController@destroy')->name('services.destroy');
    /*  Services Details */
    Route::patch('/services_details/update/{service_detail}','ServicesDetailsController@update')->name('services_detail.update');
    Route::delete('/services_details/delete/{service_detail}','ServicesDetailsController@destroy')->name('services_detail.destroy');
    /* Requirements */
    Route::get('/requirements', 'RequirementsController@index')->name('requirements.index');
    Route::get('/requirements/show/{requirement}', 'RequirementsController@show')->name('requirements.show');
    Route::resource('requirements', 'RequirementsController', ['except' => ['index', 'show']]);
    /* Users */
    Route::resource('users', 'UsersController');
    /* Resources */
    Route::resource('resources', 'ResourcesController', ['except' => ['show']]);
    /* Task */
    Route::get('/tasks/calendar','TasksController@calendar')->name('tasks.calendar');
    Route::post('/task/{requirement}/store', 'TasksController@store')->name('tasks.store');
    Route::get('/task/{task}/clickup','TasksController@Project_Task')->name('tasks.Project_Task');
    Route::post('task/{task}/project','TasksController@Project')->name('tasks.Project');
    Route::post('/task/{task}/postTask','TasksController@postTask')->name('tasks.postTask');
    Route::resource('tasks', 'TasksController', ['except' => ['create', 'store']]);
    /* Quotes */
    Route::post('/quotes/{requirement}/store', 'QuotesController@store')->name('quotes.store');
    Route::resource('quotes', 'QuotesController', ['except' => ['create', 'store']]);
    /* Quotes Details*/
    Route::post('/quotes_details/{quote}/store', 'Quotes_DetailsController@store')->name('quotes_details.store');
    Route::patch('/quotes_details/{quote_detail}/update', 'Quotes_DetailsController@update')->name('quotes_details.update');
    Route::delete('/quotes_details/{quote_detail}', 'Quotes_DetailsController@destroy')->name('quotes_details.destroy');
    /* Roles */
    Route::resource('roles', 'RolesController');

    /* Api */
    Route::get('/api/resource/{resource}', function (Resource $resource) {
        return $resource;
    });

    /* Statuses */
    Route::resource('statuses', 'StatusesController');

    /* Sources */
    Route::resource('sources', 'SourcesController');

    /* Types */
    Route::resource('types', 'TypesController');


    /* Providers */
    Route::resource('providers','ProvidersController', ['except' => ['create', 'store','edit']]);
});

app/Requirement.php
<?php

namespace App;
use App\Client;
use App\User; 
use App\Status;
use App\Source;
use Illuminate\Database\Eloquent\Model;

class Requirement extends Model
{
    protected $guarded = [];
    protected $with = ['client', 'contact', 'status','source'];

    public function client()
    {
        return $this->belongsTo('App\Client', 'client_id');
    }

    public function contact()
    {
        return $this->belongsTo('App\User', 'contact_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function status()
    {
        return $this->belongsTo('App\Status', 'status_id');
    }

    public function source()
    {
        return $this->belongsTo('App\Source','source_id');
    }

    public function tasks()
    {
        return $this->hasMany('App\Task','requirement_id');
    }

}

app/Http/Controllers/RequirementsController.php
<?php

namespace App\Http\Controllers;

use App\Type;
use App\User;
use App\Client;
use App\Source;
use App\Status;
use App\Resource;
use App\Requirement;
use Illuminate\Http\Request;

class RequirementsController extends Controller
{
    public function index(Request $request)
    {
        $clients = Client::all();
        $sources = Source::all();
        $requirements = Requirement::when($request->filled('client_id'), function ($query) use ($request) {
            return $query->where('client_id', $request->input('client_id'));
        })->when($request->filled(['from', 'to']), function ($query) use ($request) {
            return $query->whereBetween('due_date', [$request->input('from'), $request->input('to')]);
        })->when($request->filled('source_id'),function ($query) use ($request){
            return $query->where('source_id', $request->input('source_id'));
        })->get();
        return view('requirements.index', compact('requirements', 'clients', 'sources'));
    }

    public function show(Requirement $requirement)
    {
        $resources = Resource::all();
        $types = Type::all();
        $statuses = Status::all();
        return view('requirements.show', compact('requirement', 'resources', 'types', 'statuses'));
    }

    public function create()
    {
        $clients = Client::all();
        $contacts = User::all();
        $sources = Source::all();
        return view('requirements.create', compact('clients', 'contacts', 'sources'));
    }

    public function store(Request $request)
    {
        $messages = [
            'client_id.required' => 'Escoja un cliente.',
            'client_id.exists' => 'Escoja un cliente.',
            'contact_id.required' => 'Escoja un contacto.',
            'contact_id.exists' => 'Escoja un contacto.',
            'source_id.required' => 'Escoja una fuente.',
            'source_id.exists' => 'Escoja una fuente.',
            'due_date.required' => 'Escoja una fecha.',
            'description.required' => 'Rellene la descripción.'
        ];

        $request->validate([
            'client_id' => 'required|exists:clients,id',
            'contact_id' => 'required|exists:users,id',
            'due_date' => 'required',
            'description' => 'required',
            'source_id' => 'required'
        ], $messages);

        $requirement = new Requirement($request->all());
        $requirement->user_id = 2;
        $requirement->status_id = 1;
        $requirement->save();

        return redirect()->route('requirements.index')->with('success', 'La solicitud ha sido ingresada exitosamente.');
    }

    public function edit(Requirement $requirement)
    {
        $clients = Client::all();
        $contacts = User::all();
        $sources = Source::all();
        return view('requirements.edit', compact('requirement', 'clients', 'contacts', 'sources'));
    }

    public function update(Request $request, Requirement $requirement)
    {
        $messages = [
            'client_id.required' => 'Escoja un cliente.',
            'client_id.exists' => 'Escoja un cliente.',
            'contact_id.required' => 'Escoja un contacto.',
            'contact_id.exists' => 'Escoja un contacto.',
            'source_id.required' => 'Escoja una fuente.',
            'source_id.exists' => 'Escoja una fuente.',
            'due_date.required' => 'Escoja una fecha.',
            'description.required' => 'Rellene la descripción.'
        ];

        $request->validate([
            'client_id' => 'required|exists:clients,id',
            'contact_id' => 'required|exists:users,id',
            'due_date' => 'required',
            'description' => 'required',
            'source_id' => 'required'
        ], $messages);

        $requirement->update($request->all());

        return redirect()->route('requirements.index')->with('success', 'La solicitud ha sido actualizada correctamente.');
    }

    public function destroy(Requirement $requirement)
    {
        $requirement->delete();

        return redirect()->route('requirements.index')->with('success', 'La solicituda ha sido eliminada correctamente.');
    }
}

resources/views/requirements/create.blade.php
@extends('layouts.layout') @section('content')
<!-- BEGIN: Subheader -->
@breadcrumbs(['title' => 'Crear Solicitud'])
<li class="m-nav__item m-nav__item--home">
    <a href="/" class="m-nav__link m-nav__link--icon">
        <i class="m-nav__link-icon la la-home"></i>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{route('requirements.index')}}" class="m-nav__link">
        <span class="m-nav__link-text">Solicitudes</span>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{route('requirements.create')}}" class="m-nav__link">
        <span class="m-nav__link-text">Crear</span>
    </a>
</li>
@slot('options') @endslot @endbreadcrumbs
<!-- END: Subheader -->
<div class="m-content">
    <!--Section-->
    <div class="m-portlet">
        <div class="m-portlet__body m-portlet__body--no-padding">
            <div class="row m-row--no-padding m-row--col-separator-xl">
                <div class="m-section col mb-0">
                    <div class="m-section_content">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text"> Ingrese los detalles de la solicitud</h3>
                                </div>
                            </div>
                        </div>
                        <form class="m-form m-form--fit m-form--label-align-right m-form--state" method="post" action="{{route('requirements.store')}}"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="form-group m-form__group @if($errors->has('client_id')) has-danger @endif">
                                <label for="client_id">Clientes:</label>
                                <select class="form-control selectpicker col-lg-3" name="client_id" id="client_id">
                                    <option value="">Seleccionar cliente</option>
                                    @foreach($clients as $client)
                                        <option value="{{$client->id}}">{{$client->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('client_id'))
                                    <div class="form-control-feedback">{{ $errors->first('client_id') }}</div>
                                @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('contact_id')) has-danger @endif">
                                <label for="contact_id">Contactos:</label>
                                <select class="form-control selectpicker col-lg-3" name="contact_id" id="contact_id">
                                    <option value="">Seleccionar contacto</option>
                                    @foreach($contacts as $contact)
                                        <option value="{{$contact->id}}">{{$contact->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('contact_id'))
                                    <div class="form-control-feedback">{{ $errors->first('contact_id') }}</div>
                                @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('description')) has-danger @endif">
                                <label for="description">Descripción:</label>
                                <textarea class="form-control m-input summernote" name="description" id="description" cols="80" rows="5" placeholder="Ingrese descripción"></textarea>
                                @if($errors->has('description'))
                                    <div class="form-control-feedback">{{ $errors->first('description') }}</div>
                                @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('due_date')) has-danger @endif">
                                <label for="date"> Fecha de Entrega:</label>
                                <input name="due_date" class="form-control date col-lg-3" type="date" value="" id="date" readonly>
                                @if($errors->has('due_date'))
                                <div class="form-control-feedback">{{ $errors->first('due_date') }}</div>
                                @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('source_id')) has-danger @endif">
                                <label for="source_id">Fuente:</label>
                                <select class="form-control selectpicker col-lg-3" name="source_id" id="source_id">
                                    <option value="">Seleccionar fuente</option>
                                    @foreach($sources as $source)
                                        <option value="{{$source->id}}">{{$source->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('source_id'))
                                    <div class="form-control-feedback">{{ $errors->first('source_id') }}</div>
                                @endif
                            </div>
                            <div class="m-form__actions">
                                <a href="{{ route("requirements.index")}}" class="btn btn-metal">Cancelar</a>
                                <button type="submit" class="btn btn-success">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $('.date').datepicker({
            orientation: "bottom left",
            autoclose: true,
            format: "yyyy-mm-dd",
            templates: {
                leftArrow: '<i class="la la-angle-left"></i>',
                rightArrow: '<i class="la la-angle-right"></i>'
            }
        });
        $('.select').select2({
            placeholder: "Seleccionar cliente"
        });
        $('.summernote').summernote({
            height: 200
        });
    </script>
@endpush

resources/views/requirements/edit.blade.php
@extends('layouts.layout') @section('content')
<!-- BEGIN: Subheader -->
@breadcrumbs(['title' => 'Editar Solicitud'])
<li class="m-nav__item m-nav__item--home">
    <a href="/" class="m-nav__link m-nav__link--icon">
        <i class="m-nav__link-icon la la-home"></i>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{route('requirements.index')}}" class="m-nav__link">
        <span class="m-nav__link-text">Solicitudes</span>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{route('requirements.edit',[$requirement])}}" class="m-nav__link">
        <span class="m-nav__link-text">Crear</span>
    </a>
</li>
@slot('options') @endslot @endbreadcrumbs
<!-- END: Subheader -->
<div class="m-content">
    <!--Section-->
    <div class="m-portlet">
        <div class="m-portlet__body m-portlet__body--no-padding">
            <div class="row m-row--no-padding m-row--col-separator-xl">
                <div class="m-section col mb-0">
                    <div class="m-section_content">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text"> Ingrese los detalles de la solicitud</h3>
                                </div>
                            </div>
                        </div>
                        <form class="m-form m-form--fit m-form--label-align-right m-form--state" method="post" action="{{route('requirements.update', [$requirement])}}"
                            enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="form-group m-form__group @if($errors->has('client_id')) has-danger @endif">
                                <label for="client_id">Seleccione Cliente:</label>
                                <select class="form-control selectpicker col-lg-3" name="client_id" id="client_id">
                                    <option value="">Clientes</option>
                                    @foreach($clients as $client)
                                        <option value="{{$client->id}}" @if($client->id === $requirement->client_id) selected @endif>{{$client->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('client_id'))
                                    <div class="form-control-feedback">{{ $errors->first('client_id') }}</div>
                                @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('contact_id')) has-danger @endif">
                                <label for="contact_id">Seleccione Contacto:</label>
                                <select class="form-control selectpicker col-lg-3" name="contact_id" id="contact_id">
                                    <option value="">Seleccionar contacto</option>
                                    @foreach($contacts as $contact)
                                        <option value="{{$contact->id}}" @if($contact->id === $requirement->contact_id) selected @endif>{{$contact->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('contact_id'))
                                    <div class="form-control-feedback">{{ $errors->first('contact_id') }}</div>
                                @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('description')) has-danger @endif">
                                <label for="description">Descripción:</label>
                                <textarea class="form-control m-input summernote col-lg-8"name="description" id="description" cols="80" rows="5" placeholder="Ingrese descripción">{{$requirement->description}}</textarea>
                                    @if($errors->has('description'))
                                        <div class="form-control-feedback">{{ $errors->first('description') }}</div>
                                    @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('due_date')) has-danger @endif">
                                <label for="date"> Fecha:</label>
                                <input name="due_date"class="form-control date col-lg-3" type="date" value="{{$requirement->due_date}}" id="date" readonly placeholder="Ingrese fecha">
                                @if($errors->has('due_date'))
                                <div class="form-control-feedback">{{ $errors->first('due_date') }}</div>
                                @endif
                            </div>
                            <div class="form-group m-form__group @if($errors->has('source_id')) has-danger @endif">
                                <label for="source_id">Seleccione Fuente:</label>
                                <select class="form-control selectpicker col-lg-3" name="source_id" id="source_id" aria-placeholder="Seleccione Recurso">
                                    <option value="">Seleccionar fuente</option>
                                    @foreach($sources as $source)
                                        <option value="{{$source->id}}" @if($source->id === $requirement->source_id) selected @endif>{{$source->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('source_id'))
                                    <div class="form-control-feedback">{{ $errors->first('source_id') }}</div>
                                @endif
                            </div>
                            <div class="m-form__actions">
                                <a href="{{ route("requirements.index")}}" class="btn btn-metal">Cancelar</a>
                                <button type="submit" class="btn btn-success">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $('.date').datepicker({
        orientation: "bottom left",
        autoclose: true,
        format: "yyyy-mm-dd",
        templates: {
            leftArrow: '<i class="la la-angle-left"></i>',
            rightArrow: '<i class="la la-angle-right"></i>'
        }
    });
    $('#client_id').select2({
        placeholder: "Seleccionar cliente"
    });
    $('.contact_id').select2({
        placeholder: "Seleccionar contacto"
    });
    $('.source_id').select2({
        placeholder: "Seleccionar fuente"
    });

    $('.summernote').summernote({
    height: 140
});
</script>
@endpush

resources/views/requirements/index.blade.php
@extends('layouts.layout') 

@section('content')
<!-- BEGIN: Subheader -->
@breadcrumbs(['title' => 'Solicitudes'])
<li class="m-nav__item m-nav__item--home">
    <a href="/" class="m-nav__link m-nav__link--icon">
        <i class="m-nav__link-icon la la-home"></i>
    </a>
</li>
<li class="m-nav__separator">-</li>
<li class="m-nav__item">
    <a href="{{route('requirements.index')}}" class="m-nav__link">
        <span class="m-nav__link-text">Solicitudes</span>
    </a>
</li>
@slot('options')
<a href="{{ route('requirements.create') }}" class="btn btn-primary">Agregar solicitud</a>
@endslot @endbreadcrumbs
<!-- END: Subheader -->

<div class="m-content">
    <!--Section-->
    <div class="m-portlet">
        <div class="m-portlet__body m-portlet__body--no-padding">
            <div class="row m-row--no-padding m-row--col-separator-xl">
                <div class="m-section col mb-0">
                    <div class="m-section_content">
                        <form class="m-form m-form--fit m-form--label-align-right m-form--state" method="GET" action="{{ route('requirements.index') }}">
                            <div class="row d-flex p-4">
                                <div class="col-lg-3">
                                    <label for="client_id">Cliente:</label>
                                    <select class="form-control selectpicker" name="client_id" id="client_id">
                                        <option value=""> Seleccionar cliente</option>
                                        @foreach($clients as $client)
                                            <option value="{{$client->id}}">{{$client->name}}</option>
                                        @endforeach
                                    </select>
                                </div> 
                                <div class="col-lg-3">
                                    <label for="source_id">Fuente:</label>
                                    <select class="form-control selectpicker" name="source_id" id="source_id">
                                        <option value=""> Seleccionar fuente</option>
                                        @foreach($sources as $source)
                                            <option value="{{$source->id}}">{{$source->name}}</option>
                                        @endforeach
                                    </select>
                                </div>    
                                <div class="col-lg-2 align-items-center">
                                    <label for="from">Desde:</label>
                                    <input type="text" class="form-control date" name="from" id="from" readonly placeholder="Fecha desde"/>
                                </div>
                                <div class="col-lg-2 align-items-center">
                                    <label for="to">Hasta:</label>
                                    <input type="text" class="form-control date" name="to" id="to" readonly placeholder="Fecha hasta"/>
                                </div>
                                <div class="col-lg-2 d-flex align-items-end">
                                    <button class="btn btn-success">Filtrar</button>
                                </div>
                            </div>
                        </form>
                        <table class="table table-bordered m-table m-table--head-bg-brand mb-0">
                            <thead>
                                <tr>
                                    <th class="m--img-centered">#</th>
                                    <th class="m--img-centered">Cliente</th>
                                    <th class="m--img-centered">Estado</th>
                                    <th class="m--img-centered">Fecha de Entrega</th>
                                    <th class="m--img-centered">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($requirements as $requirement)
                                <tr>
                                    <td class="m--img-centered" >{{$loop->iteration}}</td>
                                    <td class="m--img-centered">{{$requirement->client->name}}</td>
                                    <td class="m--img-centered">
                                        <span class="m-badge m-badge--success m-badge--wide">{{$requirement->status->name}}</span>
                                    </td>
                                    <td class="m--img-centered">{{$requirement->due_date}}</td>
                                    <td class="m--img-centered">
                                        <a href="{{ route('requirements.show', [$requirement])}}" class="btn btn-success btn-sm">
                                            <i class="m-menu__link-icon flaticon-visible"></i>
                                            Ver
                                        </a>
                                        <a href="{{ route('requirements.edit', [$requirement])}}" class="btn btn-info btn-sm">
                                            <i class="m-menu__link-icon flaticon-edit"></i>
                                            Editar
                                        </a>

                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#eliminarModal{{$requirement->id}}">
                                            <i class="m-menu__link-icon flaticon-circle"></i>
                                            Eliminar
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="eliminarModal{{$requirement->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                            aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Eliminar Solicitud de {{ $requirement->client->name }}</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        ¿Está seguro que desea eliminar esta solicitud?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                        <form action="{{ route('requirements.destroy', [$requirement])}}" method="POST">
                                                            @csrf
                                                            @method('delete')
                                                            <button class="btn btn-primary">
                                                                Eliminar
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
    <script>
        $('.date').datepicker({
            orientation: "bottom left",
            autoclose: true,
            format: "yyyy-mm-dd",
            templates: {
                leftArrow: '<i class="la la-angle-left"></i>',
                rightArrow: '<i class="la la-angle-right"></i>'
            }
        });
        $('#client_id').select2({
            placeholder: "Seleccionar cliente"
        });
        $('#source_id').select2({
            placeholder:"Selecionar fuente"
        });
    </script>
@endpush